# Generated by cloudcoil-model-codegen; DO NOT EDIT
from importlib import import_module
from typing import TYPE_CHECKING, Literal, overload

from cloudcoil.resources import Resource

if TYPE_CHECKING:
    from cloudcoil.models.keda.eventing.v1alpha1 import CloudEventSource as _Resource0
    from cloudcoil.models.keda.eventing.v1alpha1 import ClusterCloudEventSource as _Resource1
    from cloudcoil.models.keda.v1alpha1 import ClusterTriggerAuthentication as _Resource2
    from cloudcoil.models.keda.v1alpha1 import ScaledJob as _Resource3
    from cloudcoil.models.keda.v1alpha1 import ScaledObject as _Resource4
    from cloudcoil.models.keda.v1alpha1 import TriggerAuthentication as _Resource5

_MODELS = {
    ("CloudEventSource", "eventing.keda.sh/v1alpha1"): (
        "cloudcoil.models.keda.eventing.v1alpha1",
        "CloudEventSource",
    ),
    ("CloudEventSource", ""): ("cloudcoil.models.keda.eventing.v1alpha1", "CloudEventSource"),
    ("ClusterCloudEventSource", "eventing.keda.sh/v1alpha1"): (
        "cloudcoil.models.keda.eventing.v1alpha1",
        "ClusterCloudEventSource",
    ),
    ("ClusterCloudEventSource", ""): (
        "cloudcoil.models.keda.eventing.v1alpha1",
        "ClusterCloudEventSource",
    ),
    ("ClusterTriggerAuthentication", "keda.sh/v1alpha1"): (
        "cloudcoil.models.keda.v1alpha1",
        "ClusterTriggerAuthentication",
    ),
    ("ClusterTriggerAuthentication", ""): (
        "cloudcoil.models.keda.v1alpha1",
        "ClusterTriggerAuthentication",
    ),
    ("ScaledJob", "keda.sh/v1alpha1"): ("cloudcoil.models.keda.v1alpha1", "ScaledJob"),
    ("ScaledJob", ""): ("cloudcoil.models.keda.v1alpha1", "ScaledJob"),
    ("ScaledObject", "keda.sh/v1alpha1"): ("cloudcoil.models.keda.v1alpha1", "ScaledObject"),
    ("ScaledObject", ""): ("cloudcoil.models.keda.v1alpha1", "ScaledObject"),
    ("TriggerAuthentication", "keda.sh/v1alpha1"): (
        "cloudcoil.models.keda.v1alpha1",
        "TriggerAuthentication",
    ),
    ("TriggerAuthentication", ""): ("cloudcoil.models.keda.v1alpha1", "TriggerAuthentication"),
}


@overload
def get_model(
    kind: Literal["CloudEventSource"], *, api_version: Literal["eventing.keda.sh/v1alpha1"]
) -> type[_Resource0]: ...


@overload
def get_model(
    kind: Literal["CloudEventSource"], *, api_version: Literal[""] = ""
) -> type[_Resource0]: ...


@overload
def get_model(
    kind: Literal["ClusterCloudEventSource"], *, api_version: Literal["eventing.keda.sh/v1alpha1"]
) -> type[_Resource1]: ...


@overload
def get_model(
    kind: Literal["ClusterCloudEventSource"], *, api_version: Literal[""] = ""
) -> type[_Resource1]: ...


@overload
def get_model(
    kind: Literal["ClusterTriggerAuthentication"], *, api_version: Literal["keda.sh/v1alpha1"]
) -> type[_Resource2]: ...


@overload
def get_model(
    kind: Literal["ClusterTriggerAuthentication"], *, api_version: Literal[""] = ""
) -> type[_Resource2]: ...


@overload
def get_model(
    kind: Literal["ScaledJob"], *, api_version: Literal["keda.sh/v1alpha1"]
) -> type[_Resource3]: ...


@overload
def get_model(kind: Literal["ScaledJob"], *, api_version: Literal[""] = "") -> type[_Resource3]: ...


@overload
def get_model(
    kind: Literal["ScaledObject"], *, api_version: Literal["keda.sh/v1alpha1"]
) -> type[_Resource4]: ...


@overload
def get_model(
    kind: Literal["ScaledObject"], *, api_version: Literal[""] = ""
) -> type[_Resource4]: ...


@overload
def get_model(
    kind: Literal["TriggerAuthentication"], *, api_version: Literal["keda.sh/v1alpha1"]
) -> type[_Resource5]: ...


@overload
def get_model(
    kind: Literal["TriggerAuthentication"], *, api_version: Literal[""] = ""
) -> type[_Resource5]: ...


@overload
def get_model(kind: str, *, api_version: str = "") -> type[Resource]: ...


def get_model(kind: str, *, api_version: str = "") -> type[Resource]:
    """Look up a model in this package; specify api_version for ambiguous kinds."""
    try:
        module, name = _MODELS[kind, api_version]
    except KeyError:
        raise ValueError(
            f"Unknown or ambiguous resource {kind!r}; specify a supported api_version"
        ) from None
    return getattr(import_module(module), name)
