# Generated by cloudcoil-model-codegen v0.7.0
# DO NOT EDIT

from typing import Annotated, Callable, ClassVar, Literal, overload

from cloudcoil.apimachinery import ObjectMeta
from cloudcoil.pydantic import (
    UNSET,
    BaseModel,
    BaseModelBuilder,
    BuilderContextBase,
    GenericListBuilder,
    ListBuilderContext,
    Never,
    Self,
)
from cloudcoil.resources import Resource
from pydantic import Field


class CloudEventSourceSpecAuthenticationRef(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["CloudEventSourceSpecAuthenticationRef"]:
            return CloudEventSourceSpecAuthenticationRef

        def build(self) -> "CloudEventSourceSpecAuthenticationRef":
            return CloudEventSourceSpecAuthenticationRef(**self._attrs)

        def kind(self, value: str | None, /) -> Self:
            "Kind of the resource being referred to. Defaults to TriggerAuthentication."
            return self._set("kind", value)

        def name(self, value: str, /) -> Self:
            return self._set("name", value)

    class BuilderContext(BuilderContextBase["CloudEventSourceSpecAuthenticationRef.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = CloudEventSourceSpecAuthenticationRef.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for CloudEventSourceSpecAuthenticationRef."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["CloudEventSourceSpecAuthenticationRef", Builder]:
        return GenericListBuilder[
            CloudEventSourceSpecAuthenticationRef,
            CloudEventSourceSpecAuthenticationRef.Builder,
        ]()

    kind: str | None = None
    "Kind of the resource being referred to. Defaults to TriggerAuthentication."
    name: str


class CloudEventSourceSpecDestinationAzureEventGridTopic(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["CloudEventSourceSpecDestinationAzureEventGridTopic"]:
            return CloudEventSourceSpecDestinationAzureEventGridTopic

        def build(self) -> "CloudEventSourceSpecDestinationAzureEventGridTopic":
            return CloudEventSourceSpecDestinationAzureEventGridTopic(**self._attrs)

        def endpoint(self, value: str, /) -> Self:
            return self._set("endpoint", value)

    class BuilderContext(
        BuilderContextBase["CloudEventSourceSpecDestinationAzureEventGridTopic.Builder"]
    ):
        def model_post_init(self, __context) -> None:
            self._builder = CloudEventSourceSpecDestinationAzureEventGridTopic.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for CloudEventSourceSpecDestinationAzureEventGridTopic."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["CloudEventSourceSpecDestinationAzureEventGridTopic", Builder]:
        return GenericListBuilder[
            CloudEventSourceSpecDestinationAzureEventGridTopic,
            CloudEventSourceSpecDestinationAzureEventGridTopic.Builder,
        ]()

    endpoint: str


class CloudEventSourceSpecDestinationHttp(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["CloudEventSourceSpecDestinationHttp"]:
            return CloudEventSourceSpecDestinationHttp

        def build(self) -> "CloudEventSourceSpecDestinationHttp":
            return CloudEventSourceSpecDestinationHttp(**self._attrs)

        def uri(self, value: str, /) -> Self:
            return self._set("uri", value)

    class BuilderContext(BuilderContextBase["CloudEventSourceSpecDestinationHttp.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = CloudEventSourceSpecDestinationHttp.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for CloudEventSourceSpecDestinationHttp."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["CloudEventSourceSpecDestinationHttp", Builder]:
        return GenericListBuilder[
            CloudEventSourceSpecDestinationHttp,
            CloudEventSourceSpecDestinationHttp.Builder,
        ]()

    uri: str


class CloudEventSourceSpecEventSubscription(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["CloudEventSourceSpecEventSubscription"]:
            return CloudEventSourceSpecEventSubscription

        def build(self) -> "CloudEventSourceSpecEventSubscription":
            return CloudEventSourceSpecEventSubscription(**self._attrs)

        def excluded_event_types(
            self,
            value: (
                list[
                    Literal[
                        "keda.scaledobject.ready.v1",
                        "keda.scaledobject.failed.v1",
                        "keda.scaledobject.removed.v1",
                        "keda.scaledjob.ready.v1",
                        "keda.scaledjob.failed.v1",
                        "keda.scaledjob.removed.v1",
                        "keda.authentication.triggerauthentication.created.v1",
                        "keda.authentication.triggerauthentication.updated.v1",
                        "keda.authentication.triggerauthentication.removed.v1",
                        "keda.authentication.clustertriggerauthentication.created.v1",
                        "keda.authentication.clustertriggerauthentication.updated.v1",
                        "keda.authentication.clustertriggerauthentication.removed.v1",
                    ]
                ]
                | None
            ),
            /,
        ) -> Self:
            return self._set("excluded_event_types", value)

        def included_event_types(
            self,
            value: (
                list[
                    Literal[
                        "keda.scaledobject.ready.v1",
                        "keda.scaledobject.failed.v1",
                        "keda.scaledobject.removed.v1",
                        "keda.scaledjob.ready.v1",
                        "keda.scaledjob.failed.v1",
                        "keda.scaledjob.removed.v1",
                        "keda.authentication.triggerauthentication.created.v1",
                        "keda.authentication.triggerauthentication.updated.v1",
                        "keda.authentication.triggerauthentication.removed.v1",
                        "keda.authentication.clustertriggerauthentication.created.v1",
                        "keda.authentication.clustertriggerauthentication.updated.v1",
                        "keda.authentication.clustertriggerauthentication.removed.v1",
                    ]
                ]
                | None
            ),
            /,
        ) -> Self:
            return self._set("included_event_types", value)

    class BuilderContext(BuilderContextBase["CloudEventSourceSpecEventSubscription.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = CloudEventSourceSpecEventSubscription.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for CloudEventSourceSpecEventSubscription."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["CloudEventSourceSpecEventSubscription", Builder]:
        return GenericListBuilder[
            CloudEventSourceSpecEventSubscription,
            CloudEventSourceSpecEventSubscription.Builder,
        ]()

    excluded_event_types: Annotated[
        list[
            Literal[
                "keda.scaledobject.ready.v1",
                "keda.scaledobject.failed.v1",
                "keda.scaledobject.removed.v1",
                "keda.scaledjob.ready.v1",
                "keda.scaledjob.failed.v1",
                "keda.scaledjob.removed.v1",
                "keda.authentication.triggerauthentication.created.v1",
                "keda.authentication.triggerauthentication.updated.v1",
                "keda.authentication.triggerauthentication.removed.v1",
                "keda.authentication.clustertriggerauthentication.created.v1",
                "keda.authentication.clustertriggerauthentication.updated.v1",
                "keda.authentication.clustertriggerauthentication.removed.v1",
            ]
        ]
        | None,
        Field(alias="excludedEventTypes"),
    ] = None
    included_event_types: Annotated[
        list[
            Literal[
                "keda.scaledobject.ready.v1",
                "keda.scaledobject.failed.v1",
                "keda.scaledobject.removed.v1",
                "keda.scaledjob.ready.v1",
                "keda.scaledjob.failed.v1",
                "keda.scaledjob.removed.v1",
                "keda.authentication.triggerauthentication.created.v1",
                "keda.authentication.triggerauthentication.updated.v1",
                "keda.authentication.triggerauthentication.removed.v1",
                "keda.authentication.clustertriggerauthentication.created.v1",
                "keda.authentication.clustertriggerauthentication.updated.v1",
                "keda.authentication.clustertriggerauthentication.removed.v1",
            ]
        ]
        | None,
        Field(alias="includedEventTypes"),
    ] = None


class CloudEventSourceStatusConditionsItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["CloudEventSourceStatusConditionsItem"]:
            return CloudEventSourceStatusConditionsItem

        def build(self) -> "CloudEventSourceStatusConditionsItem":
            return CloudEventSourceStatusConditionsItem(**self._attrs)

        def message(self, value: str | None, /) -> Self:
            "A human readable message indicating details about the transition."
            return self._set("message", value)

        def reason(self, value: str | None, /) -> Self:
            "The reason for the condition\u0027s last transition."
            return self._set("reason", value)

        def status(self, value: str, /) -> Self:
            "Status of the condition, one of True, False, Unknown."
            return self._set("status", value)

        def type(self, value: str, /) -> Self:
            "Type of condition"
            return self._set("type", value)

    class BuilderContext(BuilderContextBase["CloudEventSourceStatusConditionsItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = CloudEventSourceStatusConditionsItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for CloudEventSourceStatusConditionsItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["CloudEventSourceStatusConditionsItem", Builder]:
        return GenericListBuilder[
            CloudEventSourceStatusConditionsItem,
            CloudEventSourceStatusConditionsItem.Builder,
        ]()

    message: str | None = None
    "A human readable message indicating details about the transition."
    reason: str | None = None
    "The reason for the condition\u0027s last transition."
    status: str
    "Status of the condition, one of True, False, Unknown."
    type: str
    "Type of condition"


class ClusterCloudEventSourceSpecAuthenticationRef(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ClusterCloudEventSourceSpecAuthenticationRef"]:
            return ClusterCloudEventSourceSpecAuthenticationRef

        def build(self) -> "ClusterCloudEventSourceSpecAuthenticationRef":
            return ClusterCloudEventSourceSpecAuthenticationRef(**self._attrs)

        def kind(self, value: str | None, /) -> Self:
            "Kind of the resource being referred to. Defaults to TriggerAuthentication."
            return self._set("kind", value)

        def name(self, value: str, /) -> Self:
            return self._set("name", value)

    class BuilderContext(
        BuilderContextBase["ClusterCloudEventSourceSpecAuthenticationRef.Builder"]
    ):
        def model_post_init(self, __context) -> None:
            self._builder = ClusterCloudEventSourceSpecAuthenticationRef.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ClusterCloudEventSourceSpecAuthenticationRef."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["ClusterCloudEventSourceSpecAuthenticationRef", Builder]:
        return GenericListBuilder[
            ClusterCloudEventSourceSpecAuthenticationRef,
            ClusterCloudEventSourceSpecAuthenticationRef.Builder,
        ]()

    kind: str | None = None
    "Kind of the resource being referred to. Defaults to TriggerAuthentication."
    name: str


class ClusterCloudEventSourceSpecDestinationAzureEventGridTopic(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(
            self,
        ) -> type["ClusterCloudEventSourceSpecDestinationAzureEventGridTopic"]:
            return ClusterCloudEventSourceSpecDestinationAzureEventGridTopic

        def build(self) -> "ClusterCloudEventSourceSpecDestinationAzureEventGridTopic":
            return ClusterCloudEventSourceSpecDestinationAzureEventGridTopic(**self._attrs)

        def endpoint(self, value: str, /) -> Self:
            return self._set("endpoint", value)

    class BuilderContext(
        BuilderContextBase["ClusterCloudEventSourceSpecDestinationAzureEventGridTopic.Builder"]
    ):
        def model_post_init(self, __context) -> None:
            self._builder = ClusterCloudEventSourceSpecDestinationAzureEventGridTopic.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ClusterCloudEventSourceSpecDestinationAzureEventGridTopic."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["ClusterCloudEventSourceSpecDestinationAzureEventGridTopic", Builder]:
        return GenericListBuilder[
            ClusterCloudEventSourceSpecDestinationAzureEventGridTopic,
            ClusterCloudEventSourceSpecDestinationAzureEventGridTopic.Builder,
        ]()

    endpoint: str


class ClusterCloudEventSourceSpecDestinationHttp(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ClusterCloudEventSourceSpecDestinationHttp"]:
            return ClusterCloudEventSourceSpecDestinationHttp

        def build(self) -> "ClusterCloudEventSourceSpecDestinationHttp":
            return ClusterCloudEventSourceSpecDestinationHttp(**self._attrs)

        def uri(self, value: str, /) -> Self:
            return self._set("uri", value)

    class BuilderContext(BuilderContextBase["ClusterCloudEventSourceSpecDestinationHttp.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ClusterCloudEventSourceSpecDestinationHttp.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ClusterCloudEventSourceSpecDestinationHttp."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["ClusterCloudEventSourceSpecDestinationHttp", Builder]:
        return GenericListBuilder[
            ClusterCloudEventSourceSpecDestinationHttp,
            ClusterCloudEventSourceSpecDestinationHttp.Builder,
        ]()

    uri: str


class ClusterCloudEventSourceSpecEventSubscription(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ClusterCloudEventSourceSpecEventSubscription"]:
            return ClusterCloudEventSourceSpecEventSubscription

        def build(self) -> "ClusterCloudEventSourceSpecEventSubscription":
            return ClusterCloudEventSourceSpecEventSubscription(**self._attrs)

        def excluded_event_types(
            self,
            value: (
                list[
                    Literal[
                        "keda.scaledobject.ready.v1",
                        "keda.scaledobject.failed.v1",
                        "keda.scaledobject.removed.v1",
                        "keda.scaledjob.ready.v1",
                        "keda.scaledjob.failed.v1",
                        "keda.scaledjob.removed.v1",
                        "keda.authentication.triggerauthentication.created.v1",
                        "keda.authentication.triggerauthentication.updated.v1",
                        "keda.authentication.triggerauthentication.removed.v1",
                        "keda.authentication.clustertriggerauthentication.created.v1",
                        "keda.authentication.clustertriggerauthentication.updated.v1",
                        "keda.authentication.clustertriggerauthentication.removed.v1",
                    ]
                ]
                | None
            ),
            /,
        ) -> Self:
            return self._set("excluded_event_types", value)

        def included_event_types(
            self,
            value: (
                list[
                    Literal[
                        "keda.scaledobject.ready.v1",
                        "keda.scaledobject.failed.v1",
                        "keda.scaledobject.removed.v1",
                        "keda.scaledjob.ready.v1",
                        "keda.scaledjob.failed.v1",
                        "keda.scaledjob.removed.v1",
                        "keda.authentication.triggerauthentication.created.v1",
                        "keda.authentication.triggerauthentication.updated.v1",
                        "keda.authentication.triggerauthentication.removed.v1",
                        "keda.authentication.clustertriggerauthentication.created.v1",
                        "keda.authentication.clustertriggerauthentication.updated.v1",
                        "keda.authentication.clustertriggerauthentication.removed.v1",
                    ]
                ]
                | None
            ),
            /,
        ) -> Self:
            return self._set("included_event_types", value)

    class BuilderContext(
        BuilderContextBase["ClusterCloudEventSourceSpecEventSubscription.Builder"]
    ):
        def model_post_init(self, __context) -> None:
            self._builder = ClusterCloudEventSourceSpecEventSubscription.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ClusterCloudEventSourceSpecEventSubscription."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["ClusterCloudEventSourceSpecEventSubscription", Builder]:
        return GenericListBuilder[
            ClusterCloudEventSourceSpecEventSubscription,
            ClusterCloudEventSourceSpecEventSubscription.Builder,
        ]()

    excluded_event_types: Annotated[
        list[
            Literal[
                "keda.scaledobject.ready.v1",
                "keda.scaledobject.failed.v1",
                "keda.scaledobject.removed.v1",
                "keda.scaledjob.ready.v1",
                "keda.scaledjob.failed.v1",
                "keda.scaledjob.removed.v1",
                "keda.authentication.triggerauthentication.created.v1",
                "keda.authentication.triggerauthentication.updated.v1",
                "keda.authentication.triggerauthentication.removed.v1",
                "keda.authentication.clustertriggerauthentication.created.v1",
                "keda.authentication.clustertriggerauthentication.updated.v1",
                "keda.authentication.clustertriggerauthentication.removed.v1",
            ]
        ]
        | None,
        Field(alias="excludedEventTypes"),
    ] = None
    included_event_types: Annotated[
        list[
            Literal[
                "keda.scaledobject.ready.v1",
                "keda.scaledobject.failed.v1",
                "keda.scaledobject.removed.v1",
                "keda.scaledjob.ready.v1",
                "keda.scaledjob.failed.v1",
                "keda.scaledjob.removed.v1",
                "keda.authentication.triggerauthentication.created.v1",
                "keda.authentication.triggerauthentication.updated.v1",
                "keda.authentication.triggerauthentication.removed.v1",
                "keda.authentication.clustertriggerauthentication.created.v1",
                "keda.authentication.clustertriggerauthentication.updated.v1",
                "keda.authentication.clustertriggerauthentication.removed.v1",
            ]
        ]
        | None,
        Field(alias="includedEventTypes"),
    ] = None


class ClusterCloudEventSourceStatusConditionsItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ClusterCloudEventSourceStatusConditionsItem"]:
            return ClusterCloudEventSourceStatusConditionsItem

        def build(self) -> "ClusterCloudEventSourceStatusConditionsItem":
            return ClusterCloudEventSourceStatusConditionsItem(**self._attrs)

        def message(self, value: str | None, /) -> Self:
            "A human readable message indicating details about the transition."
            return self._set("message", value)

        def reason(self, value: str | None, /) -> Self:
            "The reason for the condition\u0027s last transition."
            return self._set("reason", value)

        def status(self, value: str, /) -> Self:
            "Status of the condition, one of True, False, Unknown."
            return self._set("status", value)

        def type(self, value: str, /) -> Self:
            "Type of condition"
            return self._set("type", value)

    class BuilderContext(BuilderContextBase["ClusterCloudEventSourceStatusConditionsItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ClusterCloudEventSourceStatusConditionsItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ClusterCloudEventSourceStatusConditionsItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["ClusterCloudEventSourceStatusConditionsItem", Builder]:
        return GenericListBuilder[
            ClusterCloudEventSourceStatusConditionsItem,
            ClusterCloudEventSourceStatusConditionsItem.Builder,
        ]()

    message: str | None = None
    "A human readable message indicating details about the transition."
    reason: str | None = None
    "The reason for the condition\u0027s last transition."
    status: str
    "Status of the condition, one of True, False, Unknown."
    type: str
    "Type of condition"


class CloudEventSourceStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["CloudEventSourceStatus"]:
            return CloudEventSourceStatus

        def build(self) -> "CloudEventSourceStatus":
            return CloudEventSourceStatus(**self._attrs)

        @overload
        def conditions(
            self,
            value_or_callback: list[CloudEventSourceStatusConditionsItem] | None,
            /,
        ) -> "CloudEventSourceStatus.Builder": ...

        @overload
        def conditions(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        CloudEventSourceStatusConditionsItem,
                        CloudEventSourceStatusConditionsItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    CloudEventSourceStatusConditionsItem,
                    CloudEventSourceStatusConditionsItem.Builder,
                ]
                | list[CloudEventSourceStatusConditionsItem],
            ],
            /,
        ) -> "CloudEventSourceStatus.Builder": ...

        @overload
        def conditions(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[CloudEventSourceStatusConditionsItem.Builder]: ...

        def conditions(self, value_or_callback=UNSET, /):
            "Conditions an array representation to store multiple Conditions"
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[CloudEventSourceStatusConditionsItem.Builder]()
                context._parent_builder = self
                context._field_name = "conditions"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(CloudEventSourceStatusConditionsItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("conditions", value)

    class BuilderContext(BuilderContextBase["CloudEventSourceStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = CloudEventSourceStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for CloudEventSourceStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["CloudEventSourceStatus", Builder]:
        return GenericListBuilder[CloudEventSourceStatus, CloudEventSourceStatus.Builder]()

    conditions: list[CloudEventSourceStatusConditionsItem] | None = None
    "Conditions an array representation to store multiple Conditions"


class ClusterCloudEventSourceStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ClusterCloudEventSourceStatus"]:
            return ClusterCloudEventSourceStatus

        def build(self) -> "ClusterCloudEventSourceStatus":
            return ClusterCloudEventSourceStatus(**self._attrs)

        @overload
        def conditions(
            self,
            value_or_callback: list[ClusterCloudEventSourceStatusConditionsItem] | None,
            /,
        ) -> "ClusterCloudEventSourceStatus.Builder": ...

        @overload
        def conditions(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        ClusterCloudEventSourceStatusConditionsItem,
                        ClusterCloudEventSourceStatusConditionsItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    ClusterCloudEventSourceStatusConditionsItem,
                    ClusterCloudEventSourceStatusConditionsItem.Builder,
                ]
                | list[ClusterCloudEventSourceStatusConditionsItem],
            ],
            /,
        ) -> "ClusterCloudEventSourceStatus.Builder": ...

        @overload
        def conditions(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[ClusterCloudEventSourceStatusConditionsItem.Builder]: ...

        def conditions(self, value_or_callback=UNSET, /):
            "Conditions an array representation to store multiple Conditions"
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[ClusterCloudEventSourceStatusConditionsItem.Builder]()
                context._parent_builder = self
                context._field_name = "conditions"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(
                    ClusterCloudEventSourceStatusConditionsItem.list_builder()
                )
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("conditions", value)

    class BuilderContext(BuilderContextBase["ClusterCloudEventSourceStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ClusterCloudEventSourceStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ClusterCloudEventSourceStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["ClusterCloudEventSourceStatus", Builder]:
        return GenericListBuilder[
            ClusterCloudEventSourceStatus, ClusterCloudEventSourceStatus.Builder
        ]()

    conditions: list[ClusterCloudEventSourceStatusConditionsItem] | None = None
    "Conditions an array representation to store multiple Conditions"


class CloudEventSourceSpecDestination(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["CloudEventSourceSpecDestination"]:
            return CloudEventSourceSpecDestination

        def build(self) -> "CloudEventSourceSpecDestination":
            return CloudEventSourceSpecDestination(**self._attrs)

        @overload
        def azure_event_grid_topic(
            self,
            value_or_callback: (CloudEventSourceSpecDestinationAzureEventGridTopic | None),
            /,
        ) -> "CloudEventSourceSpecDestination.Builder": ...

        @overload
        def azure_event_grid_topic(
            self,
            value_or_callback: Callable[
                [CloudEventSourceSpecDestinationAzureEventGridTopic.Builder],
                CloudEventSourceSpecDestinationAzureEventGridTopic.Builder
                | CloudEventSourceSpecDestinationAzureEventGridTopic,
            ],
            /,
        ) -> "CloudEventSourceSpecDestination.Builder": ...

        @overload
        def azure_event_grid_topic(
            self, value_or_callback: Never = ...
        ) -> "CloudEventSourceSpecDestinationAzureEventGridTopic.BuilderContext": ...

        def azure_event_grid_topic(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = CloudEventSourceSpecDestinationAzureEventGridTopic.BuilderContext()
                context._parent_builder = self
                context._field_name = "azure_event_grid_topic"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(
                    CloudEventSourceSpecDestinationAzureEventGridTopic.builder()
                )
                if isinstance(output, CloudEventSourceSpecDestinationAzureEventGridTopic.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("azure_event_grid_topic", value)

        @overload
        def http(
            self, value_or_callback: CloudEventSourceSpecDestinationHttp | None, /
        ) -> "CloudEventSourceSpecDestination.Builder": ...

        @overload
        def http(
            self,
            value_or_callback: Callable[
                [CloudEventSourceSpecDestinationHttp.Builder],
                CloudEventSourceSpecDestinationHttp.Builder | CloudEventSourceSpecDestinationHttp,
            ],
            /,
        ) -> "CloudEventSourceSpecDestination.Builder": ...

        @overload
        def http(
            self, value_or_callback: Never = ...
        ) -> "CloudEventSourceSpecDestinationHttp.BuilderContext": ...

        def http(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = CloudEventSourceSpecDestinationHttp.BuilderContext()
                context._parent_builder = self
                context._field_name = "http"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(CloudEventSourceSpecDestinationHttp.builder())
                if isinstance(output, CloudEventSourceSpecDestinationHttp.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("http", value)

    class BuilderContext(BuilderContextBase["CloudEventSourceSpecDestination.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = CloudEventSourceSpecDestination.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for CloudEventSourceSpecDestination."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["CloudEventSourceSpecDestination", Builder]:
        return GenericListBuilder[
            CloudEventSourceSpecDestination, CloudEventSourceSpecDestination.Builder
        ]()

    azure_event_grid_topic: Annotated[
        CloudEventSourceSpecDestinationAzureEventGridTopic | None,
        Field(alias="azureEventGridTopic"),
    ] = None
    http: CloudEventSourceSpecDestinationHttp | None = None


class ClusterCloudEventSourceSpecDestination(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ClusterCloudEventSourceSpecDestination"]:
            return ClusterCloudEventSourceSpecDestination

        def build(self) -> "ClusterCloudEventSourceSpecDestination":
            return ClusterCloudEventSourceSpecDestination(**self._attrs)

        @overload
        def azure_event_grid_topic(
            self,
            value_or_callback: (ClusterCloudEventSourceSpecDestinationAzureEventGridTopic | None),
            /,
        ) -> "ClusterCloudEventSourceSpecDestination.Builder": ...

        @overload
        def azure_event_grid_topic(
            self,
            value_or_callback: Callable[
                [ClusterCloudEventSourceSpecDestinationAzureEventGridTopic.Builder],
                ClusterCloudEventSourceSpecDestinationAzureEventGridTopic.Builder
                | ClusterCloudEventSourceSpecDestinationAzureEventGridTopic,
            ],
            /,
        ) -> "ClusterCloudEventSourceSpecDestination.Builder": ...

        @overload
        def azure_event_grid_topic(
            self, value_or_callback: Never = ...
        ) -> "ClusterCloudEventSourceSpecDestinationAzureEventGridTopic.BuilderContext": ...

        def azure_event_grid_topic(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ClusterCloudEventSourceSpecDestinationAzureEventGridTopic.BuilderContext()
                context._parent_builder = self
                context._field_name = "azure_event_grid_topic"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(
                    ClusterCloudEventSourceSpecDestinationAzureEventGridTopic.builder()
                )
                if isinstance(
                    output,
                    ClusterCloudEventSourceSpecDestinationAzureEventGridTopic.Builder,
                ):
                    value = output.build()
                else:
                    value = output
            return self._set("azure_event_grid_topic", value)

        @overload
        def http(
            self,
            value_or_callback: ClusterCloudEventSourceSpecDestinationHttp | None,
            /,
        ) -> "ClusterCloudEventSourceSpecDestination.Builder": ...

        @overload
        def http(
            self,
            value_or_callback: Callable[
                [ClusterCloudEventSourceSpecDestinationHttp.Builder],
                ClusterCloudEventSourceSpecDestinationHttp.Builder
                | ClusterCloudEventSourceSpecDestinationHttp,
            ],
            /,
        ) -> "ClusterCloudEventSourceSpecDestination.Builder": ...

        @overload
        def http(
            self, value_or_callback: Never = ...
        ) -> "ClusterCloudEventSourceSpecDestinationHttp.BuilderContext": ...

        def http(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ClusterCloudEventSourceSpecDestinationHttp.BuilderContext()
                context._parent_builder = self
                context._field_name = "http"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ClusterCloudEventSourceSpecDestinationHttp.builder())
                if isinstance(output, ClusterCloudEventSourceSpecDestinationHttp.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("http", value)

    class BuilderContext(BuilderContextBase["ClusterCloudEventSourceSpecDestination.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ClusterCloudEventSourceSpecDestination.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ClusterCloudEventSourceSpecDestination."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["ClusterCloudEventSourceSpecDestination", Builder]:
        return GenericListBuilder[
            ClusterCloudEventSourceSpecDestination,
            ClusterCloudEventSourceSpecDestination.Builder,
        ]()

    azure_event_grid_topic: Annotated[
        ClusterCloudEventSourceSpecDestinationAzureEventGridTopic | None,
        Field(alias="azureEventGridTopic"),
    ] = None
    http: ClusterCloudEventSourceSpecDestinationHttp | None = None


class CloudEventSourceSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["CloudEventSourceSpec"]:
            return CloudEventSourceSpec

        def build(self) -> "CloudEventSourceSpec":
            return CloudEventSourceSpec(**self._attrs)

        @overload
        def authentication_ref(
            self, value_or_callback: CloudEventSourceSpecAuthenticationRef | None, /
        ) -> "CloudEventSourceSpec.Builder": ...

        @overload
        def authentication_ref(
            self,
            value_or_callback: Callable[
                [CloudEventSourceSpecAuthenticationRef.Builder],
                CloudEventSourceSpecAuthenticationRef.Builder
                | CloudEventSourceSpecAuthenticationRef,
            ],
            /,
        ) -> "CloudEventSourceSpec.Builder": ...

        @overload
        def authentication_ref(
            self, value_or_callback: Never = ...
        ) -> "CloudEventSourceSpecAuthenticationRef.BuilderContext": ...

        def authentication_ref(self, value_or_callback=UNSET, /):
            "AuthenticationRef points to the TriggerAuthentication or ClusterTriggerAuthentication object that\nis used to authenticate the scaler with the environment"
            if self._in_context and value_or_callback is UNSET:
                context = CloudEventSourceSpecAuthenticationRef.BuilderContext()
                context._parent_builder = self
                context._field_name = "authentication_ref"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(CloudEventSourceSpecAuthenticationRef.builder())
                if isinstance(output, CloudEventSourceSpecAuthenticationRef.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("authentication_ref", value)

        def cluster_name(self, value: str | None, /) -> Self:
            return self._set("cluster_name", value)

        @overload
        def destination(
            self, value_or_callback: CloudEventSourceSpecDestination, /
        ) -> "CloudEventSourceSpec.Builder": ...

        @overload
        def destination(
            self,
            value_or_callback: Callable[
                [CloudEventSourceSpecDestination.Builder],
                CloudEventSourceSpecDestination.Builder | CloudEventSourceSpecDestination,
            ],
            /,
        ) -> "CloudEventSourceSpec.Builder": ...

        @overload
        def destination(
            self, value_or_callback: Never = ...
        ) -> "CloudEventSourceSpecDestination.BuilderContext": ...

        def destination(self, value_or_callback=UNSET, /):
            "Destination defines the various ways to emit events"
            if self._in_context and value_or_callback is UNSET:
                context = CloudEventSourceSpecDestination.BuilderContext()
                context._parent_builder = self
                context._field_name = "destination"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(CloudEventSourceSpecDestination.builder())
                if isinstance(output, CloudEventSourceSpecDestination.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("destination", value)

        @overload
        def event_subscription(
            self, value_or_callback: CloudEventSourceSpecEventSubscription | None, /
        ) -> "CloudEventSourceSpec.Builder": ...

        @overload
        def event_subscription(
            self,
            value_or_callback: Callable[
                [CloudEventSourceSpecEventSubscription.Builder],
                CloudEventSourceSpecEventSubscription.Builder
                | CloudEventSourceSpecEventSubscription,
            ],
            /,
        ) -> "CloudEventSourceSpec.Builder": ...

        @overload
        def event_subscription(
            self, value_or_callback: Never = ...
        ) -> "CloudEventSourceSpecEventSubscription.BuilderContext": ...

        def event_subscription(self, value_or_callback=UNSET, /):
            "EventSubscription defines filters for events"
            if self._in_context and value_or_callback is UNSET:
                context = CloudEventSourceSpecEventSubscription.BuilderContext()
                context._parent_builder = self
                context._field_name = "event_subscription"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(CloudEventSourceSpecEventSubscription.builder())
                if isinstance(output, CloudEventSourceSpecEventSubscription.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("event_subscription", value)

    class BuilderContext(BuilderContextBase["CloudEventSourceSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = CloudEventSourceSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for CloudEventSourceSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["CloudEventSourceSpec", Builder]:
        return GenericListBuilder[CloudEventSourceSpec, CloudEventSourceSpec.Builder]()

    authentication_ref: Annotated[
        CloudEventSourceSpecAuthenticationRef | None, Field(alias="authenticationRef")
    ] = None
    "AuthenticationRef points to the TriggerAuthentication or ClusterTriggerAuthentication object that\nis used to authenticate the scaler with the environment"
    cluster_name: Annotated[str | None, Field(alias="clusterName")] = None
    destination: CloudEventSourceSpecDestination
    "Destination defines the various ways to emit events"
    event_subscription: Annotated[
        CloudEventSourceSpecEventSubscription | None, Field(alias="eventSubscription")
    ] = None
    "EventSubscription defines filters for events"


class ClusterCloudEventSourceSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ClusterCloudEventSourceSpec"]:
            return ClusterCloudEventSourceSpec

        def build(self) -> "ClusterCloudEventSourceSpec":
            return ClusterCloudEventSourceSpec(**self._attrs)

        @overload
        def authentication_ref(
            self,
            value_or_callback: ClusterCloudEventSourceSpecAuthenticationRef | None,
            /,
        ) -> "ClusterCloudEventSourceSpec.Builder": ...

        @overload
        def authentication_ref(
            self,
            value_or_callback: Callable[
                [ClusterCloudEventSourceSpecAuthenticationRef.Builder],
                ClusterCloudEventSourceSpecAuthenticationRef.Builder
                | ClusterCloudEventSourceSpecAuthenticationRef,
            ],
            /,
        ) -> "ClusterCloudEventSourceSpec.Builder": ...

        @overload
        def authentication_ref(
            self, value_or_callback: Never = ...
        ) -> "ClusterCloudEventSourceSpecAuthenticationRef.BuilderContext": ...

        def authentication_ref(self, value_or_callback=UNSET, /):
            "AuthenticationRef points to the TriggerAuthentication or ClusterTriggerAuthentication object that\nis used to authenticate the scaler with the environment"
            if self._in_context and value_or_callback is UNSET:
                context = ClusterCloudEventSourceSpecAuthenticationRef.BuilderContext()
                context._parent_builder = self
                context._field_name = "authentication_ref"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ClusterCloudEventSourceSpecAuthenticationRef.builder())
                if isinstance(output, ClusterCloudEventSourceSpecAuthenticationRef.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("authentication_ref", value)

        def cluster_name(self, value: str | None, /) -> Self:
            return self._set("cluster_name", value)

        @overload
        def destination(
            self, value_or_callback: ClusterCloudEventSourceSpecDestination, /
        ) -> "ClusterCloudEventSourceSpec.Builder": ...

        @overload
        def destination(
            self,
            value_or_callback: Callable[
                [ClusterCloudEventSourceSpecDestination.Builder],
                ClusterCloudEventSourceSpecDestination.Builder
                | ClusterCloudEventSourceSpecDestination,
            ],
            /,
        ) -> "ClusterCloudEventSourceSpec.Builder": ...

        @overload
        def destination(
            self, value_or_callback: Never = ...
        ) -> "ClusterCloudEventSourceSpecDestination.BuilderContext": ...

        def destination(self, value_or_callback=UNSET, /):
            "Destination defines the various ways to emit events"
            if self._in_context and value_or_callback is UNSET:
                context = ClusterCloudEventSourceSpecDestination.BuilderContext()
                context._parent_builder = self
                context._field_name = "destination"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ClusterCloudEventSourceSpecDestination.builder())
                if isinstance(output, ClusterCloudEventSourceSpecDestination.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("destination", value)

        @overload
        def event_subscription(
            self,
            value_or_callback: ClusterCloudEventSourceSpecEventSubscription | None,
            /,
        ) -> "ClusterCloudEventSourceSpec.Builder": ...

        @overload
        def event_subscription(
            self,
            value_or_callback: Callable[
                [ClusterCloudEventSourceSpecEventSubscription.Builder],
                ClusterCloudEventSourceSpecEventSubscription.Builder
                | ClusterCloudEventSourceSpecEventSubscription,
            ],
            /,
        ) -> "ClusterCloudEventSourceSpec.Builder": ...

        @overload
        def event_subscription(
            self, value_or_callback: Never = ...
        ) -> "ClusterCloudEventSourceSpecEventSubscription.BuilderContext": ...

        def event_subscription(self, value_or_callback=UNSET, /):
            "EventSubscription defines filters for events"
            if self._in_context and value_or_callback is UNSET:
                context = ClusterCloudEventSourceSpecEventSubscription.BuilderContext()
                context._parent_builder = self
                context._field_name = "event_subscription"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ClusterCloudEventSourceSpecEventSubscription.builder())
                if isinstance(output, ClusterCloudEventSourceSpecEventSubscription.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("event_subscription", value)

    class BuilderContext(BuilderContextBase["ClusterCloudEventSourceSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ClusterCloudEventSourceSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ClusterCloudEventSourceSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ClusterCloudEventSourceSpec", Builder]:
        return GenericListBuilder[
            ClusterCloudEventSourceSpec, ClusterCloudEventSourceSpec.Builder
        ]()

    authentication_ref: Annotated[
        ClusterCloudEventSourceSpecAuthenticationRef | None,
        Field(alias="authenticationRef"),
    ] = None
    "AuthenticationRef points to the TriggerAuthentication or ClusterTriggerAuthentication object that\nis used to authenticate the scaler with the environment"
    cluster_name: Annotated[str | None, Field(alias="clusterName")] = None
    destination: ClusterCloudEventSourceSpecDestination
    "Destination defines the various ways to emit events"
    event_subscription: Annotated[
        ClusterCloudEventSourceSpecEventSubscription | None,
        Field(alias="eventSubscription"),
    ] = None
    "EventSubscription defines filters for events"


class CloudEventSource(Resource):
    __cloudcoil_api__: ClassVar[dict] = {
        "plural": "cloudeventsources",
        "scope": "Namespaced",
        "status": True,
    }

    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["CloudEventSource"]:
            return CloudEventSource

        def build(self) -> "CloudEventSource":
            return CloudEventSource(**self._attrs)

        def api_version(self, value: Literal["eventing.keda.sh/v1alpha1"], /) -> Self:
            "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        def kind(self, value: Literal["CloudEventSource"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(
            self, value_or_callback: ObjectMeta | None, /
        ) -> "CloudEventSource.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "CloudEventSource.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

        @overload
        def spec(
            self, value_or_callback: CloudEventSourceSpec, /
        ) -> "CloudEventSource.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[
                [CloudEventSourceSpec.Builder],
                CloudEventSourceSpec.Builder | CloudEventSourceSpec,
            ],
            /,
        ) -> "CloudEventSource.Builder": ...

        @overload
        def spec(self, value_or_callback: Never = ...) -> "CloudEventSourceSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = CloudEventSourceSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(CloudEventSourceSpec.builder())
                if isinstance(output, CloudEventSourceSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

        @overload
        def status(
            self, value_or_callback: CloudEventSourceStatus | None, /
        ) -> "CloudEventSource.Builder": ...

        @overload
        def status(
            self,
            value_or_callback: Callable[
                [CloudEventSourceStatus.Builder],
                CloudEventSourceStatus.Builder | CloudEventSourceStatus,
            ],
            /,
        ) -> "CloudEventSource.Builder": ...

        @overload
        def status(
            self, value_or_callback: Never = ...
        ) -> "CloudEventSourceStatus.BuilderContext": ...

        def status(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = CloudEventSourceStatus.BuilderContext()
                context._parent_builder = self
                context._field_name = "status"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(CloudEventSourceStatus.builder())
                if isinstance(output, CloudEventSourceStatus.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("status", value)

    class BuilderContext(BuilderContextBase["CloudEventSource.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = CloudEventSource.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for CloudEventSource."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["CloudEventSource", Builder]:
        return GenericListBuilder[CloudEventSource, CloudEventSource.Builder]()

    api_version: Annotated[Literal["eventing.keda.sh/v1alpha1"], Field(alias="apiVersion")] = (
        "eventing.keda.sh/v1alpha1"
    )
    "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    kind: Literal["CloudEventSource"] = "CloudEventSource"
    "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None
    spec: CloudEventSourceSpec
    status: CloudEventSourceStatus | None = None


class ClusterCloudEventSource(Resource):
    __cloudcoil_api__: ClassVar[dict] = {
        "plural": "clustercloudeventsources",
        "scope": "Cluster",
        "status": True,
    }

    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ClusterCloudEventSource"]:
            return ClusterCloudEventSource

        def build(self) -> "ClusterCloudEventSource":
            return ClusterCloudEventSource(**self._attrs)

        def api_version(self, value: Literal["eventing.keda.sh/v1alpha1"], /) -> Self:
            "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        def kind(self, value: Literal["ClusterCloudEventSource"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(
            self, value_or_callback: ObjectMeta | None, /
        ) -> "ClusterCloudEventSource.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "ClusterCloudEventSource.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

        @overload
        def spec(
            self, value_or_callback: ClusterCloudEventSourceSpec, /
        ) -> "ClusterCloudEventSource.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[
                [ClusterCloudEventSourceSpec.Builder],
                ClusterCloudEventSourceSpec.Builder | ClusterCloudEventSourceSpec,
            ],
            /,
        ) -> "ClusterCloudEventSource.Builder": ...

        @overload
        def spec(
            self, value_or_callback: Never = ...
        ) -> "ClusterCloudEventSourceSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ClusterCloudEventSourceSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ClusterCloudEventSourceSpec.builder())
                if isinstance(output, ClusterCloudEventSourceSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

        @overload
        def status(
            self, value_or_callback: ClusterCloudEventSourceStatus | None, /
        ) -> "ClusterCloudEventSource.Builder": ...

        @overload
        def status(
            self,
            value_or_callback: Callable[
                [ClusterCloudEventSourceStatus.Builder],
                ClusterCloudEventSourceStatus.Builder | ClusterCloudEventSourceStatus,
            ],
            /,
        ) -> "ClusterCloudEventSource.Builder": ...

        @overload
        def status(
            self, value_or_callback: Never = ...
        ) -> "ClusterCloudEventSourceStatus.BuilderContext": ...

        def status(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ClusterCloudEventSourceStatus.BuilderContext()
                context._parent_builder = self
                context._field_name = "status"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ClusterCloudEventSourceStatus.builder())
                if isinstance(output, ClusterCloudEventSourceStatus.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("status", value)

    class BuilderContext(BuilderContextBase["ClusterCloudEventSource.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ClusterCloudEventSource.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ClusterCloudEventSource."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ClusterCloudEventSource", Builder]:
        return GenericListBuilder[ClusterCloudEventSource, ClusterCloudEventSource.Builder]()

    api_version: Annotated[Literal["eventing.keda.sh/v1alpha1"], Field(alias="apiVersion")] = (
        "eventing.keda.sh/v1alpha1"
    )
    "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    kind: Literal["ClusterCloudEventSource"] = "ClusterCloudEventSource"
    "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None
    spec: ClusterCloudEventSourceSpec
    status: ClusterCloudEventSourceStatus | None = None
